#requires -Version 7.4
# Rulebook.Levels: the organization side and the documentation side of levels (WP10, D25, D26, D29, D49).
# New-RulebookOffLevel writes the everything-off root level an organization adds itself (there is no shipped one,
# D25); Get-RulebookLevelSummary is the model of one level page (its rows, its basedOn and its counts per stage) and
# New-RulebookLevelDocs writes the Markdown pages from it for any repository. tools/rulebook/Build-Template.ps1 writes
# the pages of the shipped levels into docs/levels/ of this repository; the WP14 site builds an organization's own
# pages from the same model. Contract and recipes: docs/authoring-levels.md.

Set-StrictMode -Version 3.0
Import-Module (Join-Path $PSScriptRoot 'Rulebook.Generate.psd1')
Import-Module (Join-Path $PSScriptRoot 'Rulebook.Catalog.psd1')
# Sync-GeneratedFolder, the folder writer of the template generators.
Import-Module (Join-Path $PSScriptRoot 'Rulebook.Template.psd1')

$script:DeltaSchemaUrl = 'https://raw.githubusercontent.com/ALCops/rulebook-engine/v1/schemas/ruleset.delta.schema.json'
$script:SettingsPath = '.github/Rulebook-Settings.json'
$script:CatalogPath = 'catalog/diagnostics.json'
$script:OffSettingsDescription = 'Every known diagnostic off. Opt in through overrides.'
$script:Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
# Strictness order of docs/rulebook/00-conventions.md section 2; a row whose action ranks below its From is lowered.
$script:ActionRank = [System.Collections.Generic.Dictionary[string, int]]::new([System.StringComparer]::Ordinal)
$script:ActionRank['None'] = 0
$script:ActionRank['Hidden'] = 1
$script:ActionRank['Info'] = 2
$script:ActionRank['Warning'] = 3
$script:ActionRank['Error'] = 4
$script:CountActions = @('Error', 'Warning', 'Info', 'Hidden', 'None')
# A line within the first five lines of every page and index New-RulebookLevelDocs writes (Get-GeneratedLine).
$script:GeneratedMarker = '^Generated by (`New-RulebookLevelDocs`|`[^`]+` \(`New-RulebookLevelDocs`\)) from .*; do not edit\.$'

#region Internal helpers

function Get-OrdinalMap {
    # An insertion-ordered map with ordinal keys ([ordered]@{} compares keys case-insensitively).
    return , [System.Collections.Specialized.OrderedDictionary]::new([System.StringComparer]::Ordinal)
}

function Assert-LevelSlug {
    # The slug of a level name: lowercased, matching ^[a-z0-9-]+$ (C5). Returns the slug.
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Name)
    $slug = $Name.ToLowerInvariant()
    if ($slug -cnotmatch '^[a-z0-9-]+\z') { throw "Level name '$Name' does not lowercase to a slug matching ^[a-z0-9-]+$ (C5)" }
    return $slug
}

function Get-OffLevelDescription {
    # The description of the off level file: no date, so the text is byte-stable for one catalog.
    # scripts/New-RulebookOffLevel.ps1 builds the same sentence; its suite pins the bytes.
    param([Parameter(Mandatory)][string]$Slug, [Parameter(Mandatory)][int]$Count)
    return ('Level {0}, the root. Every diagnostic the analyzers enable by default, at None ({1} ids from {2}). Written once by New-RulebookOffLevel and owned by this repository: opt in with overrides scoped to levels ["{0}"] or by editing this file. Ids newer than this file arrive through quarantine.' -f $Slug, $Count, $script:CatalogPath)
}

function Format-Cell {
    # Text for a Markdown table cell: &, < and > as HTML entities (a title such as '<>' cannot render as a tag),
    # pipes escaped, line breaks folded into spaces.
    param([AllowNull()][AllowEmptyString()][string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    $text = $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
    return ($text -replace '[\r\n]+', ' ').Replace('|', '\|')
}

function Format-Line {
    # Free text for one Markdown line: line breaks folded into spaces.
    param([AllowNull()][AllowEmptyString()][string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return '' }
    return $Text -replace '[\r\n]+', ' '
}

function Format-LinkUrl {
    # A URL for a Markdown link target: the characters that could end the link, the cell or the autolink early are
    # percent-encoded.
    param([Parameter(Mandatory)][string]$Url)
    return $Url.Replace('(', '%28').Replace(')', '%29').Replace('|', '%7C').Replace('<', '%3C').Replace('>', '%3E').Replace(']', '%5D') -replace '\s', '%20'
}

function Format-LinkText {
    # Text for a Markdown link label inside a table cell: a cell, with the brackets escaped too.
    param([AllowNull()][AllowEmptyString()][string]$Text)
    return (Format-Cell $Text).Replace('[', '\[').Replace(']', '\]')
}

function Assert-CatalogEnabledFlag {
    # Every catalog entry must carry a boolean enabledByDefault (the catalog schema and C14 require it).
    # Read-CatalogFile defaults a missing one to true; the off level would then list an id the analyzers may not
    # enable. Same message as scripts/New-RulebookOffLevel.ps1.
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
    try {
        $json = [System.IO.File]::ReadAllText($Path, $script:Utf8NoBom) | ConvertFrom-Json -AsHashtable -Depth 20 -ErrorAction Stop
    } catch {
        return
    }
    if ($json -isnot [System.Collections.IDictionary] -or $json['diagnostics'] -isnot [System.Collections.IList]) { return }
    foreach ($entry in $json['diagnostics']) {
        # An entry that is not an object or has no id is left to Read-CatalogFile and its own message.
        if ($entry -isnot [System.Collections.IDictionary] -or [string]::IsNullOrEmpty([string]$entry['id'])) { continue }
        if (-not $entry.Contains('enabledByDefault') -or $entry['enabledByDefault'] -isnot [bool]) {
            throw "$($script:CatalogPath): $([string]$entry['id']) has no boolean enabledByDefault"
        }
    }
}

function Test-SettingsListing {
    # Whether the settings list a level with this slug. Read only for that flag: an unreadable settings file warns
    # and counts as not listed.
    param([Parameter(Mandatory)][string]$Root, [Parameter(Mandatory)][string]$Slug)
    $settingsPath = Join-Path $Root $script:SettingsPath
    if (-not (Test-Path -LiteralPath $settingsPath -PathType Leaf)) { return $false }
    try {
        $settings = [System.IO.File]::ReadAllText($settingsPath, $script:Utf8NoBom) | ConvertFrom-Json -AsHashtable -Depth 10 -ErrorAction Stop
    } catch {
        Write-Warning "Cannot read $($script:SettingsPath) ($($_.Exception.Message)); the level counts as not listed"
        return $false
    }
    if ($settings -isnot [System.Collections.IDictionary]) { return $false }
    foreach ($level in @($settings['levels'] | Where-Object { $_ -is [System.Collections.IDictionary] })) {
        $levelName = [string]$level['name']
        if ($levelName -and $levelName.ToLowerInvariant() -ceq $Slug) { return $true }
    }
    return $false
}

function Assert-GeneratedFolder {
    # New-RulebookLevelDocs deletes the *.md files it does not produce; it refuses a folder holding a Markdown file
    # that is not one of its pages (pointing -OutputPath at docs/ would otherwise delete hand-written pages).
    param([Parameter(Mandatory)][string]$Directory)
    if (-not (Test-Path -LiteralPath $Directory -PathType Container)) { return }
    $folder = Split-Path -Leaf $Directory
    foreach ($file in Get-ChildItem -LiteralPath $Directory -File -Filter '*.md') {
        if ($file.Name -notlike '*.md') { continue }
        $head = @(Get-Content -LiteralPath $file.FullName -TotalCount 5 -ErrorAction Stop)
        if (-not @($head | Where-Object { $_ -match $script:GeneratedMarker })) {
            throw "New-RulebookLevelDocs refuses to manage $folder/$($file.Name): it is not a generated level page"
        }
    }
}

function Get-ActionRank {
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Action, [Parameter(Mandatory)][string]$Id)
    if (-not $script:ActionRank.ContainsKey($Action)) { throw "Unknown action '$Action' for $Id" }
    return $script:ActionRank[$Action]
}

function Get-LevelLink {
    # The Markdown link of a published level page, or the slug in code when the level has no settings entry.
    param([Parameter(Mandatory)]$Summary)
    if ($Summary.BasedOnPublished) { return '[{0}]({1}.md)' -f (Format-LinkText $Summary.BasedOnName), $Summary.BasedOn }
    return '`{0}`' -f $Summary.BasedOn
}

function Get-GeneratedLine {
    param([Parameter(Mandatory)][string]$GeneratedBy, [Parameter(Mandatory)][string]$Sources)
    $by = if ($GeneratedBy -ceq 'New-RulebookLevelDocs') { '`New-RulebookLevelDocs`' } else { '`{0}` (`New-RulebookLevelDocs`)' -f $GeneratedBy }
    return "Generated by $by from $Sources; do not edit."
}

function Get-EntryNoun {
    param([Parameter(Mandatory)][int]$Count)
    if ($Count -eq 1) { return '1 entry' }
    return "$Count entries"
}

#endregion

#region Off level

function Get-RulebookOffLevelEntry {
    <#
    .SYNOPSIS
    The entries of an everything-off root level: every catalog id the analyzers enable by default, at None.
    .DESCRIPTION
    -Catalog is a Rulebook.Catalog (Read-CatalogFile). Ids with enabledByDefault false are left out (they are off
    already); Hidden defaults, deprecated and unadvertised ids are included. Ordered by Get-SortedCatalogEntry, as
    { Id, Action = 'None' } without a justification (D40). Pure.
    #>
    [CmdletBinding()]
    [OutputType([object[]])]
    param([Parameter(Mandatory)]$Catalog)
    $entries = [System.Collections.Generic.List[object]]::new()
    foreach ($entry in (Get-SortedCatalogEntry -Catalog $Catalog)) {
        if ($entry.EnabledByDefault) { $entries.Add([pscustomobject]@{ Id = $entry.Id; Action = 'None' }) }
    }
    return , $entries.ToArray()
}

function New-RulebookOffLevel {
    <#
    .SYNOPSIS
    Writes base/<slug>.ruleset.json, a root level that sets every diagnostic enabled by default to None (D25).
    .DESCRIPTION
    Reads catalog/diagnostics.json of -RepositoryRoot and writes the level file under the name 'Rulebook <Name>',
    with the delta profile URL in $schema, the entries of Get-RulebookOffLevelEntry and no justification. The file
    is owned by the organization (the update never overwrites it). Byte-stable: equal bytes return nothing; a
    differing file throws unless -Force is set. Does not edit the settings; SettingsListed reports whether the
    settings already list the level, and SettingsEntry is the JSON line to paste first into levels. Returns a
    Rulebook.OffLevel { File, Path, Change (created, modified), Name, Slug, Count, SettingsListed, SettingsEntry }.
    -WhatIf writes nothing and still returns the object. On a current file (equal bytes) nothing is returned: take
    the settings entry from the output of scripts/New-RulebookOffLevel.ps1 or write it by hand. A catalog entry
    without a boolean enabledByDefault throws (C14). The settings are not required (the script requires them as its
    are-you-in-the-right-folder check): a missing settings file gives SettingsListed $false, an unreadable one warns
    and gives SettingsListed
    $false. The file is written to <file>.tmp and moved into place. scripts/New-RulebookOffLevel.ps1 is the
    self-contained download-and-run copy of this function.
    .PARAMETER Description
    The description of the printed settings entry; default 'Every known diagnostic off. Opt in through overrides.'
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType('Rulebook.OffLevel')]
    param(
        [Parameter(Mandatory)][string]$RepositoryRoot,
        [string]$Name = 'Off',
        [string]$Description = $script:OffSettingsDescription,
        [switch]$Force
    )
    $slug = Assert-LevelSlug -Name $Name
    if ($slug -ceq 'readme') { throw "Level '$Name' cannot have a page: its slug collides with the index README.md" }
    $root = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($RepositoryRoot)
    $catalogPath = Join-Path $root $script:CatalogPath
    Assert-CatalogEnabledFlag -Path $catalogPath
    $catalog = Read-CatalogFile -Path $catalogPath
    $entries = Get-RulebookOffLevelEntry -Catalog $catalog
    if ($entries.Count -eq 0) { Write-Warning "$($script:CatalogPath) lists no diagnostic enabled by default; base/$slug.ruleset.json gets an empty rules array" }
    $text = ConvertTo-RulesetJson -Name "Rulebook $Name" -Description (Get-OffLevelDescription -Slug $slug -Count $entries.Count) -Rules $entries -Schema $script:DeltaSchemaUrl
    $bytes = $script:Utf8NoBom.GetBytes($text)

    $file = "base/$slug.ruleset.json"
    $path = Join-Path $root 'base' "$slug.ruleset.json"
    $listed = Test-SettingsListing -Root $root -Slug $slug
    $change = 'created'
    if (Test-Path -LiteralPath $path -PathType Leaf) {
        if ([System.Linq.Enumerable]::SequenceEqual([byte[]][System.IO.File]::ReadAllBytes($path), [byte[]]$bytes)) { return }
        if ($listed) { Write-Warning "'$Name' is already a published level; -Force would replace $file with an everything-off file" }
        if (-not $Force) { throw "$file exists and differs; it is owned by this repository. Use -Force to overwrite it (your own edits in it are lost)" }
        $change = 'modified'
    }

    if ($PSCmdlet.ShouldProcess($file, "Write the off level ($change)")) {
        $parent = Split-Path -Parent $path
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) { [void][System.IO.Directory]::CreateDirectory($parent) }
        try {
            [System.IO.File]::WriteAllBytes("$path.tmp", $bytes)
            [System.IO.File]::Move("$path.tmp", $path, $true)
        } catch {
            Remove-Item -LiteralPath "$path.tmp" -Force -ErrorAction SilentlyContinue
            throw
        }
    } elseif (-not $WhatIfPreference) {
        return
    }
    return [pscustomobject]@{
        PSTypeName     = 'Rulebook.OffLevel'
        File           = $file
        Path           = $path
        Change         = $change
        Name           = $Name
        Slug           = $slug
        Count          = $entries.Count
        SettingsListed = $listed
        SettingsEntry  = '{ "name": ' + (ConvertTo-JsonString $Name) + ', "description": ' + (ConvertTo-JsonString $Description) + ' }'
    }
}

#endregion

#region Level pages

function Get-RulebookLevelSummary {
    <#
    .SYNOPSIS
    The model of one level page: the level's entries against the chain below it, and its counts per stage.
    .DESCRIPTION
    -Inputs is a Rulebook.Inputs (Read-RulebookInputs), -Catalog the Rulebook.Catalog of the same repository
    (Read-CatalogFile, for analyzer, title and docs), -Level a published slug. Returns a Rulebook.LevelSummary
    { Name, Slug, Description, BasedOn, BasedOnName, BasedOnPublished, ChainFiles (root first), File, EntryCount,
    LoweredCount, TwinsSetting, OverrideCount, Rows, Groups, Counts }.

    Rows: one per entry of the level file, sorted by Get-DiagnosticSortKey: { Id, Analyzer, Title, Docs, From,
    FromSource, To, Lowered, Justification }. From is the action of the files below on the chain (last file wins,
    FromSource level:<slug>), else the analyzer default (FromSource default); $null for an id not in the catalog.
    Lowered: To ranks below From (None < Hidden < Info < Warning < Error). Groups: { Analyzer, Count, Rows } in
    order of first appearance. Counts: one per settings stage { Stage, Error, Warning, Info, Hidden, None, Listed }
    over every catalog id (overrides, twins and quarantine included); Listed is the entry count of the endpoint.
    Pure; the WP14 site builds an organization's pages from it.
    #>
    [CmdletBinding()]
    [OutputType('Rulebook.LevelSummary')]
    param([Parameter(Mandatory)]$Inputs, [Parameter(Mandatory)]$Catalog, [Parameter(Mandatory)][string]$Level)
    $entry = $null
    foreach ($item in $Inputs.Levels) { if ($item.Slug -ceq $Level) { $entry = $item } }
    if ($null -eq $entry) { throw "Unknown level slug '$Level'" }

    $basedOnName = $null
    $basedOnPublished = $false
    if ($null -ne $entry.BasedOn) {
        $basedOnName = $entry.BasedOn
        foreach ($item in $Inputs.Levels) {
            if ($item.Slug -ceq $entry.BasedOn) { $basedOnName = $item.Name; $basedOnPublished = $true }
        }
    }
    [string[]]$chainFiles = @($Inputs.ChainFiles[$Level])
    $levelFile = $Inputs.LevelFiles[$Level]

    $sorted = [System.Collections.Generic.SortedDictionary[string, object]]::new([System.StringComparer]::Ordinal)
    foreach ($rule in $levelFile.Rules.GetEnumerator()) {
        $id = [string]$rule.Key
        $from = $null
        $fromSource = $null
        for ($i = $chainFiles.Count - 2; $i -ge 0; $i--) {
            $lower = $Inputs.LevelFiles[$chainFiles[$i]].Rules
            if ($lower.Contains($id)) {
                $from = $lower[$id].Action
                $fromSource = "level:$($chainFiles[$i])"
                break
            }
        }
        if ($null -eq $fromSource) {
            $from = Get-AnalyzerDefault -Catalog $Inputs.Catalog -Id $id
            $fromSource = 'default'
        }
        $catalogEntry = if ($Catalog.Entries.Contains($id)) { $Catalog.Entries[$id] } else { $null }
        $analyzer = if ($null -ne $catalogEntry -and -not [string]::IsNullOrEmpty($catalogEntry.Analyzer)) { $catalogEntry.Analyzer } else { ([regex]::Match($id, '^[A-Za-z]+')).Value }
        $to = $rule.Value.Action
        $sorted[(Get-DiagnosticSortKey -Id $id) + '|' + $id] = [pscustomobject]@{
            Id            = $id
            Analyzer      = $analyzer
            Title         = if ($null -ne $catalogEntry -and $null -ne $catalogEntry.Title) { $catalogEntry.Title } else { '' }
            Docs          = if ($null -ne $catalogEntry -and $null -ne $catalogEntry.Docs) { $catalogEntry.Docs } else { '' }
            From          = $from
            FromSource    = $fromSource
            To            = $to
            Lowered       = ($null -ne $from) -and ((Get-ActionRank -Action $to -Id $id) -lt (Get-ActionRank -Action $from -Id $id))
            Justification = $rule.Value.Justification
        }
    }
    $rows = @($sorted.Values)

    $groupMap = Get-OrdinalMap
    foreach ($row in $rows) {
        if (-not $groupMap.Contains($row.Analyzer)) { $groupMap[$row.Analyzer] = [System.Collections.Generic.List[object]]::new() }
        $groupMap[$row.Analyzer].Add($row)
    }
    $groups = @(foreach ($key in $groupMap.Keys) { [pscustomobject]@{ Analyzer = $key; Count = $groupMap[$key].Count; Rows = $groupMap[$key].ToArray() } })

    $overrideCount = @($Inputs.Overrides | Where-Object {
            ($_.Levels.Count -eq 1 -and $_.Levels[0] -eq '*') -or ($Level -cin $_.Levels)
        }).Count

    $counts = @(foreach ($stage in $Inputs.Stages) {
            $endpoint = Get-RulebookEndpoint -Inputs $Inputs -Level $Level -Stage $stage.Slug
            $tally = @{ Error = 0; Warning = 0; Info = 0; Hidden = 0; None = 0 }
            foreach ($id in $Inputs.Catalog.Keys) {
                $action = if ($endpoint.Table.Contains($id)) { $endpoint.Table[$id].Action } else { Get-AnalyzerDefault -Catalog $Inputs.Catalog -Id $id }
                $tally[$action]++
            }
            [pscustomobject]@{
                Stage   = $stage.Slug
                Error   = $tally['Error']
                Warning = $tally['Warning']
                Info    = $tally['Info']
                Hidden  = $tally['Hidden']
                None    = $tally['None']
                Listed  = $endpoint.Entries.Count
            }
        })

    return [pscustomobject]@{
        PSTypeName       = 'Rulebook.LevelSummary'
        Name             = $entry.Name
        Slug             = $Level
        Description      = $entry.Description
        BasedOn          = $entry.BasedOn
        BasedOnName      = $basedOnName
        BasedOnPublished = $basedOnPublished
        ChainFiles       = $chainFiles
        File             = "base/$Level.ruleset.json"
        EntryCount       = $rows.Count
        LoweredCount     = @($rows | Where-Object Lowered).Count
        TwinsSetting     = $Inputs.TwinsSetting
        OverrideCount    = $overrideCount
        CatalogCount     = $Inputs.Catalog.Count
        Rows             = $rows
        Groups           = $groups
        Counts           = $counts
    }
}

function ConvertTo-LevelDocsMarkdown {
    <#
    .SYNOPSIS
    The Markdown page of one level from its Rulebook.LevelSummary.
    .DESCRIPTION
    Headings: '# Level <Name>', '## Counts per stage', '## Entries' with one '### <Analyzer> (<count>)' table per
    group (| Id | Title | From | To | Change | Justification | Docs |). A level file without entries gets one sentence
    instead of the tables. Deterministic: no date, no machine path, LF, one trailing newline.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)]$Summary, [string]$GeneratedBy = 'New-RulebookLevelDocs')
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Level $($Summary.Name)")
    $lines.Add('')
    $lines.Add((Get-GeneratedLine -GeneratedBy $GeneratedBy -Sources ('the settings, `{0}`, the chain below it and `{1}`' -f $Summary.File, $script:CatalogPath)))
    $lines.Add('')
    $lines.Add(('- **Slug:** `{0}`' -f $Summary.Slug))
    $relativeTo = 'the analyzer default'
    if ($null -eq $Summary.BasedOn) {
        $lines.Add('- **Based on:** the analyzer defaults (a root)')
    } elseif ($Summary.BasedOnPublished) {
        $lines.Add("- **Based on:** $(Get-LevelLink -Summary $Summary)")
        $relativeTo = $Summary.BasedOnName
    } else {
        $lines.Add(('- **Based on:** `{0}` (a level file without a settings entry; a root for this chain, D29)' -f $Summary.BasedOn))
        $relativeTo = '`{0}`' -f $Summary.BasedOn
    }
    $description = if ([string]::IsNullOrWhiteSpace([string]$Summary.Description)) { '(none)' } else { Format-Line ([string]$Summary.Description) }
    $lines.Add("- **Description:** $description")
    $lines.Add(('- **File:** `{0}`, {1}, {2} of them lower the action relative to {3}' -f $Summary.File, (Get-EntryNoun $Summary.EntryCount), $Summary.LoweredCount, $relativeTo))
    $lines.Add('- **Chain:** ' + (@($Summary.ChainFiles | ForEach-Object { '`base/{0}.ruleset.json`' -f $_ }) -join ' -> '))
    $lines.Add('')

    $lines.Add('## Counts per stage')
    $lines.Add('')
    $lines.Add('| Stage | Error | Warning | Info | Hidden | None | Listed |')
    $lines.Add('|---|---|---|---|---|---|---|')
    foreach ($count in $Summary.Counts) {
        $lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f $count.Stage, $count.Error, $count.Warning, $count.Info, $count.Hidden, $count.None, $count.Listed))
    }
    $lines.Add('')
    $lines.Add(('{0} catalog ids per row. Listed is the number of ids the endpoint writes (`rulesets/{1}` for default, `rulesets/{2}` for the others): ids whose action differs from the analyzer default, plus ids the level file mentions that are not in the catalog. The counts include this repository''s overrides ({3} match this level), the twins setting `{4}` and the quarantine files; the entries below are the level file alone.' -f
            $Summary.CatalogCount, (Get-EndpointFileName -Level $Summary.Slug -Stage 'default'), (Get-EndpointFileName -Level $Summary.Slug -Stage '<stage>'), $Summary.OverrideCount, $Summary.TwinsSetting))
    $lines.Add('')

    $lines.Add('## Entries')
    $lines.Add('')
    if ($Summary.EntryCount -eq 0) {
        if ($null -eq $Summary.BasedOn) {
            $lines.Add(('`{0}` lists no entry: this level is the analyzer defaults.' -f $Summary.File))
        } else {
            $lines.Add(('`{0}` lists no entry: this level is an alias of {1} and its endpoints equal that level''s.' -f $Summary.File, $(if ($Summary.BasedOnPublished) { Get-LevelLink -Summary $Summary } else { $relativeTo })))
        }
        $lines.Add('')
    } else {
        foreach ($group in $Summary.Groups) {
            $lines.Add("### $(Format-Cell $group.Analyzer) ($($group.Count))")
            $lines.Add('')
            $lines.Add('| Id | Title | From | To | Change | Justification | Docs |')
            $lines.Add('|---|---|---|---|---|---|---|')
            foreach ($row in $group.Rows) {
                $from = if ($null -ne $row.From) { $row.From } else { '(not in the catalog)' }
                $change = if ($row.Lowered) { 'lowered' } else { '' }
                $docs = if ([string]::IsNullOrEmpty($row.Docs)) { '' } else { '[docs]({0})' -f (Format-LinkUrl $row.Docs) }
                $lines.Add(('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f (Format-Cell $row.Id), (Format-Cell $row.Title), (Format-Cell $from), (Format-Cell $row.To), $change, (Format-Cell $row.Justification), $docs))
            }
            $lines.Add('')
        }
    }
    # One trailing newline: the last empty line becomes the final LF.
    return (($lines -join "`n").TrimEnd("`n")) + "`n"
}

function ConvertTo-LevelDocsIndexMarkdown {
    <#
    .SYNOPSIS
    The README.md index of the level pages: one row per published level in settings order, and the stages.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][AllowEmptyCollection()][object[]]$Summaries, [Parameter(Mandatory)]$Inputs, [string]$GeneratedBy = 'New-RulebookLevelDocs')
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Levels')
    $lines.Add('')
    $lines.Add((Get-GeneratedLine -GeneratedBy $GeneratedBy -Sources ('the settings, the level files in `base/` and `{0}`' -f $script:CatalogPath)))
    $lines.Add('')
    $lines.Add('| Level | Slug | Based on | Entries | Listed (default) | Page |')
    $lines.Add('|---|---|---|---|---|---|')
    foreach ($summary in $Summaries) {
        $basedOn = if ($null -eq $summary.BasedOn) { 'the analyzer defaults' } elseif ($summary.BasedOnPublished) { Get-LevelLink -Summary $summary } else { '`{0}` (no settings entry)' -f $summary.BasedOn }
        $default = @($summary.Counts | Where-Object Stage -CEQ 'default')
        $listed = if ($default.Count -gt 0) { [string]$default[0].Listed } else { '' }
        $lines.Add(('| {0} | `{1}` | {2} | {3} | {4} | [{1}.md]({1}.md) |' -f (Format-Cell $summary.Name), $summary.Slug, $basedOn, $summary.EntryCount, $listed))
    }
    $lines.Add('')
    $stages = @(foreach ($stage in $Inputs.Stages) {
            if ($stage.Slug -ceq 'default') {
                '`default` (the level result)'
            } else {
                $count = if ($Inputs.StageDeltas.Contains($stage.Slug)) { $Inputs.StageDeltas[$stage.Slug].Count } else { 0 }
                '`{0}` (`stages/{0}.json`, {1})' -f $stage.Slug, (Get-EntryNoun $count)
            }
        })
    $lines.Add("Stages: $($stages -join ', ').")
    return ($lines -join "`n") + "`n"
}

function New-RulebookLevelDocs {
    <#
    .SYNOPSIS
    Writes one Markdown page per published level of a repository and the README.md index into -OutputPath.
    .DESCRIPTION
    Reads the repository's inputs (Read-RulebookInputs) and catalog, builds Get-RulebookLevelSummary per level in
    settings order and writes <slug>.md plus README.md through Sync-GeneratedFolder: other *.md files in the folder
    are deleted, only files whose bytes differ are written (UTF-8 without BOM, LF). Returns one
    Rulebook.TemplateChange per change; -WhatIf writes nothing and returns the same list. Throws when the settings are
    missing, when a level's slug is 'readme' (its page would be the index) and, before writing anything, when the
    folder holds a Markdown file that is not a generated level page. tools/rulebook/Build-Template.ps1 runs it on template/ into docs/levels/ of this repository (D49).
    #>
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseSingularNouns', '', Justification = 'Writes the whole page set; name fixed by issue #12')]
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType('Rulebook.TemplateChange')]
    param(
        [Parameter(Mandatory)][string]$RepositoryRoot,
        [Parameter(Mandatory)][string]$OutputPath,
        [string]$GeneratedBy = 'New-RulebookLevelDocs'
    )
    $inputs = Read-RulebookInputs -RepositoryRoot $RepositoryRoot
    if (-not $inputs.SettingsPresent) { throw "Settings missing: $($script:SettingsPath) in $($inputs.Root)" }
    $catalog = Read-CatalogFile -Path (Join-Path $inputs.Root $script:CatalogPath)
    $directory = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)

    foreach ($level in $inputs.Levels) {
        # On a case-insensitive file system readme.md is the index README.md.
        if ($level.Slug -ceq 'readme') { throw "Level '$($level.Name)' cannot have a page: its slug collides with the index README.md" }
    }
    Assert-GeneratedFolder -Directory $directory

    $files = Get-OrdinalMap
    $summaries = [System.Collections.Generic.List[object]]::new()
    foreach ($level in $inputs.Levels) {
        $summary = Get-RulebookLevelSummary -Inputs $inputs -Catalog $catalog -Level $level.Slug
        $summaries.Add($summary)
        $files["$($level.Slug).md"] = ConvertTo-LevelDocsMarkdown -Summary $summary -GeneratedBy $GeneratedBy
    }
    $files['README.md'] = ConvertTo-LevelDocsIndexMarkdown -Summaries $summaries.ToArray() -Inputs $inputs -GeneratedBy $GeneratedBy

    # Module functions do not see this function's preference variables, so -WhatIf is passed on, and -Confirm only
    # when the caller asked for it (otherwise the caller's ConfirmPreference applies as it is).
    $sync = @{ Directory = $directory; Filter = '*.md'; Files = $files; WhatIf = [bool]$WhatIfPreference }
    if ($PSBoundParameters.ContainsKey('Confirm') -and [bool]$PSBoundParameters['Confirm']) { $sync['Confirm'] = $true }
    Sync-GeneratedFolder @sync
}

#endregion

Export-ModuleMember -Function @(
    'ConvertTo-LevelDocsIndexMarkdown'
    'ConvertTo-LevelDocsMarkdown'
    'Get-RulebookLevelSummary'
    'Get-RulebookOffLevelEntry'
    'New-RulebookLevelDocs'
    'New-RulebookOffLevel'
)
